config/routes.rb
Rails.application.routes.draw do
  devise_for :supporters
  root to: 'supporters#new'

  get "/pages/:page" => "pages#show"

  namespace :admin do
    get '/map', to: 'pages#map', as: :map
    resources :publicities
    # resources :supporters, only: :index
  end

  localized do
    #resources :greendays
    #get '/initiative_text', to: 'pages#show', as: :initiative_text, page: 'initiative_text'
    get '/terms_and_conditions', to: 'pages#show', as: :terms_and_conditions, page: 'terms_and_conditions'
    #get '/donation', to: 'pages#show', as: :donation, page: 'donation'
  end

  get '/cities_autocomplete', to: 'cities_autocomplete#index', as: :cities_autocomplete
  scope '/:locale',  locale: /de|it|fr/ do
    get '/', to: 'supporters#new'
    resources :supporters, only: [:new, :create]
    resource :publicity
    get '/thanks', to: 'pages#thanks', as: :thanks
    resources :charges
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/models/publicity.rb
class Publicity
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip

  has_mongoid_attached_file :avatar,
                            path: ':attachment/:id/:style.:extension',
                            styles: {
                              original: ['1920x1680>', :jpg],
                              small:    ['100x100#',   :jpg],
                              medium:   ['250x250',    :jpg],
                              large:    ['500x500>',   :jpg]
                            },
                            convert_options: { all: '-background white -flatten +matte' }

  embedded_in :supporter

  field :state, type: String, default: 'pending' # Possible states: pending, approved
  field :organisation, type: String
  field :statement, type: String

  validates :state,     presence: true
  validates :avatar,    presence: true
  validates :statement, presence: true
  validates_attachment_content_type :avatar, content_type: /\Aimage/
end

app/controllers/admin/publicities_controller.rb
module Admin
  class PublicitiesController < Admin::ApplicationController
    def index
      @pending = Supporter.where('publicity.state' => :pending).asc(:created_at)
      @active = Supporter.where('publicity.state' => :approved).asc(:created_at)
    end

    def edit
      @publicity = Supporter.find(params[:id]).publicity
    end

    def update
      @publicity = Supporter.find(params[:id]).publicity
      return redirect_to(admin_publicities_path) if @publicity.update_attributes(publicity_params)
      render :edit
    end

    def destroy
      current_supporter.publicity&.destroy
      redirect_to(admin_publicities_path)
    end

    private

    def publicity_params
      params.require(:publicity).permit(:organisation, :statement, :avatar, :state)
    end
  end
end

app/controllers/publicities_controller.rb
class PublicitiesController < ApplicationController
  before_action :authenticate_supporter!

  def new
    @publicity = current_supporter.publicity || Publicity.new
  end

  def create
    @publicity = Publicity.new(publicity_params.merge(supporter: current_supporter, state: :pending))
    flash['success'] = t('.success') if @publicity.valid?
    return redirect_to(root_path) if @publicity.save
    render :new
  end

  def update
    create
  end

  def destroy
    current_supporter.publicity&.destroy
    redirect_to(root_path)
  end

  private

  def publicity_params
    params.require(:publicity).permit(:organisation, :statement, :avatar)
  end
end

app/views/admin/publicities/_form.slim
h1= title "#{t('.title')} #{@publicity.supporter.first_name} #{@publicity.supporter.last_name}, #{@publicity.supporter.city}"
= simple_form_for(@publicity, url: admin_publicity_path(@publicity.supporter)) do |form|
  .form-group
    = "#{@publicity.supporter.first_name} #{@publicity.supporter.last_name}, #{@publicity.supporter.city}"

  = form.input :organisation, required: false
  = form.input :statement, as: :text, required: false
  = form.input :avatar, as: :file, required: false
  - if @publicity.avatar
    .form-group
      = image_tag(@publicity.avatar.url(:medium))
  = form.input :state, as: :radio_buttons, collection: t('publicity_states').map{ |x| [x.first, raw(x.last)]}, label_method: :last, value_method: :first, required: false
  = form.submit t('shared.save'), class: 'btn btn-primary'
  

app/views/admin/publicities/edit.slim
= render 'form'

app/views/admin/publicities/index.slim
h1 = title t('.title')
table.table
  tbody
    - @pending.each do | supporter |
      tr
        td 
          = "#{supporter.first_name} #{supporter.last_name}"
          br
          = supporter.city
          br
          = mail_to supporter.email, supporter.email
          br
          = supporter.publicity.organisation
        td width="50%" = supporter.publicity.statement
        td = image_tag(supporter.publicity.avatar.url(:small))
        td = link_to t('shared.edit'), edit_admin_publicity_path(supporter)


    